name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

autolabeler:
  - label: 'breaking'
    title:
      - '/^[a-z]+(\(.+\))?!: /'
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?: /'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?: /'
  - label: 'performance'
    title:
      - '/^perf(\(.+\))?: /'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?: /'
  - label: 'refactor'
    title:
      - '/^refactor(\(.+\))?: /'
  - label: 'chore'
    title:
      - '/^(chore|style|test|build|ci|revert)(\(.+\))?: /'

categories:
  - title: 'Breaking changes'
    labels: ['breaking']
  - title: 'Features'
    labels: ['feature']
  - title: 'Fixes'
    labels: ['fix']
  - title: 'Performance'
    labels: ['performance']
  - title: 'Documentation'
    labels: ['documentation']
  - title: 'Refactors'
    labels: ['refactor']
  - title: 'Chores'
    labels: ['chore']

version-resolver:
  major:
    labels: ['breaking']
  minor:
    labels: ['feature']
  patch:
    labels: ['fix', 'performance', 'documentation', 'refactor', 'chore']
  default: patch

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'

exclude-labels:
  - 'skip-changelog'

template: |
  ## What changed in $RESOLVED_VERSION

  $CHANGES

  **Full diff**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
