name: Update draft release notes

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches: [dev]

permissions:
  contents: read

jobs:
  update-draft:
    name: Update draft release notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v7.3.0
        with:
          commitish: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
